name: Formula CI
# this workflow will
# - test repo with python 2.7
# - test repo with python 3.6
# - deliver the package content to the configured repository
# - submit the new package content to the upstream repository
on: [push, pull_request]
env:
  PACKAGE_NAME: salt-shaptools
jobs:

  testPython2:
    runs-on: ubuntu-18.04
    #if: ${{ github.event_name != 'pull_request' }} 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test python version 2.7
      run: |
        sudo apt-get install python-minimal
        sudo python2 -V
        sudo apt-get install python-pip
        sudo -H pip --version
        sudo -H pip install --upgrade pytest
        sudo -H pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado pytest-salt mock pytest-cov enum34
        sudo git clone --depth=50 https://github.com/openSUSE/salt ../salt
        sudo rm ../salt/tests/conftest.py
        sudo git clone --depth=50 https://github.com/SUSE/shaptools.git ../shaptools
        sudo -H pip install -e ../salt
        sudo -H pip install ../shaptools
    -  run: sudo /home/runner/work/salt-shaptools/salt-shaptools/tests/run.sh

  testPython3:
    runs-on: ubuntu-18.04
    #if: ${{ github.event_name != 'pull_request' }} 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test python version 3.6
      run: |
        sudo apt-get install python3.6
        python -V   
        sudo apt-get install python-pip
        sudo -H pip install --upgrade pytest
        sudo -H pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado pytest-salt mock pytest-cov enum34
        sudo git clone --depth=50 https://github.com/openSUSE/salt ../salt
        sudo rm ../salt/tests/conftest.py
        sudo git clone --depth=50 https://github.com/SUSE/shaptools.git ../shaptools
        sudo -H pip install -e ../salt
        sudo -H pip install ../shaptools
    -  run: sudo apt-get install curl
    -  run: sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter  
    -  run: chmod +x ./cc-test-reporter
    -  run: ./cc-test-reporter before-build
    -  run: sudo /home/runner/work/salt-shaptools/salt-shaptools/tests/run.sh
      
  delivery:
    needs: [testPython2,testPython3]
    runs-on: ubuntu-18.04
    #if: ${{ github.event_name != 'pull_request' }}
    container: 
      image: shap/continuous_deliver
      env:
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
    steps:
    - uses: actions/checkout@v2 
      with:
        fetch-depth: 0
    - name: configure OSC  
    # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
    # that is used to run osc commands 
      run: | 
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: deliver package
      run: |
        sed -i 's~%%VERSION%%~${{ github.sha }}~' _service && \
        sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' _service && \
        /scripts/upload.sh 


  submit:
    needs: [testPython2,testPython3, delivery]
    runs-on: ubuntu-18.04
    #if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}    
    container:
      image: shap/continuous_deliver
      env:
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: ${{ secrets.OBS_PROJECT}}
        TARGET_PROJECT: ${{ secrets.TARGET_PROJECT}}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: configure OSC
    # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
    # that is used to run osc commands 
      run: | 
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: submit package
      run: |
       sed -i 's~%%VERSION%%~${{ github.sha }}~' _service && \
       sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' _service && \
       /scripts/submit.sh